/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package bank;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-06-18")
public class AccountManagement {

  public interface Iface {

    public AccountDetails createAccount(Account account) throws InvalidArgumentException, MissingArgumentException, org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void createAccount(Account account, org.apache.thrift.async.AsyncMethodCallback<AccountDetails> resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public AccountDetails createAccount(Account account) throws InvalidArgumentException, MissingArgumentException, org.apache.thrift.TException
    {
      send_createAccount(account);
      return recv_createAccount();
    }

    public void send_createAccount(Account account) throws org.apache.thrift.TException
    {
      createAccount_args args = new createAccount_args();
      args.setAccount(account);
      sendBase("createAccount", args);
    }

    public AccountDetails recv_createAccount() throws InvalidArgumentException, MissingArgumentException, org.apache.thrift.TException
    {
      createAccount_result result = new createAccount_result();
      receiveBase(result, "createAccount");
      if (result.isSetSuccess()) {
        return result.success;
      }
      if (result.invalidArgumentException != null) {
        throw result.invalidArgumentException;
      }
      if (result.missingArgumentException != null) {
        throw result.missingArgumentException;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "createAccount failed: unknown result");
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void createAccount(Account account, org.apache.thrift.async.AsyncMethodCallback<AccountDetails> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      createAccount_call method_call = new createAccount_call(account, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class createAccount_call extends org.apache.thrift.async.TAsyncMethodCall<AccountDetails> {
      private Account account;
      public createAccount_call(Account account, org.apache.thrift.async.AsyncMethodCallback<AccountDetails> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.account = account;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("createAccount", org.apache.thrift.protocol.TMessageType.CALL, 0));
        createAccount_args args = new createAccount_args();
        args.setAccount(account);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public AccountDetails getResult() throws InvalidArgumentException, MissingArgumentException, org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new java.lang.IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_createAccount();
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final org.slf4j.Logger _LOGGER = org.slf4j.LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new java.util.HashMap<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, java.util.Map<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> java.util.Map<java.lang.String,  org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> getProcessMap(java.util.Map<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("createAccount", new createAccount());
      return processMap;
    }

    public static class createAccount<I extends Iface> extends org.apache.thrift.ProcessFunction<I, createAccount_args> {
      public createAccount() {
        super("createAccount");
      }

      public createAccount_args getEmptyArgsInstance() {
        return new createAccount_args();
      }

      protected boolean isOneway() {
        return false;
      }

      @Override
      protected boolean rethrowUnhandledExceptions() {
        return false;
      }

      public createAccount_result getResult(I iface, createAccount_args args) throws org.apache.thrift.TException {
        createAccount_result result = new createAccount_result();
        try {
          result.success = iface.createAccount(args.account);
        } catch (InvalidArgumentException invalidArgumentException) {
          result.invalidArgumentException = invalidArgumentException;
        } catch (MissingArgumentException missingArgumentException) {
          result.missingArgumentException = missingArgumentException;
        }
        return result;
      }
    }

  }

  public static class AsyncProcessor<I extends AsyncIface> extends org.apache.thrift.TBaseAsyncProcessor<I> {
    private static final org.slf4j.Logger _LOGGER = org.slf4j.LoggerFactory.getLogger(AsyncProcessor.class.getName());
    public AsyncProcessor(I iface) {
      super(iface, getProcessMap(new java.util.HashMap<java.lang.String, org.apache.thrift.AsyncProcessFunction<I, ? extends org.apache.thrift.TBase, ?>>()));
    }

    protected AsyncProcessor(I iface, java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends AsyncIface> java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase,?>> getProcessMap(java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      processMap.put("createAccount", new createAccount());
      return processMap;
    }

    public static class createAccount<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, createAccount_args, AccountDetails> {
      public createAccount() {
        super("createAccount");
      }

      public createAccount_args getEmptyArgsInstance() {
        return new createAccount_args();
      }

      public org.apache.thrift.async.AsyncMethodCallback<AccountDetails> getResultHandler(final org.apache.thrift.server.AbstractNonblockingServer.AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new org.apache.thrift.async.AsyncMethodCallback<AccountDetails>() { 
          public void onComplete(AccountDetails o) {
            createAccount_result result = new createAccount_result();
            result.success = o;
            try {
              fcall.sendResponse(fb, result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
            } catch (org.apache.thrift.transport.TTransportException e) {
              _LOGGER.error("TTransportException writing to internal frame buffer", e);
              fb.close();
            } catch (java.lang.Exception e) {
              _LOGGER.error("Exception writing to internal frame buffer", e);
              onError(e);
            }
          }
          public void onError(java.lang.Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TSerializable msg;
            createAccount_result result = new createAccount_result();
            if (e instanceof InvalidArgumentException) {
              result.invalidArgumentException = (InvalidArgumentException) e;
              result.setInvalidArgumentExceptionIsSet(true);
              msg = result;
            } else if (e instanceof MissingArgumentException) {
              result.missingArgumentException = (MissingArgumentException) e;
              result.setMissingArgumentExceptionIsSet(true);
              msg = result;
            } else if (e instanceof org.apache.thrift.transport.TTransportException) {
              _LOGGER.error("TTransportException inside handler", e);
              fb.close();
              return;
            } else if (e instanceof org.apache.thrift.TApplicationException) {
              _LOGGER.error("TApplicationException inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TApplicationException)e;
            } else {
              _LOGGER.error("Exception inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
            } catch (java.lang.Exception ex) {
              _LOGGER.error("Exception writing to internal frame buffer", ex);
              fb.close();
            }
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, createAccount_args args, org.apache.thrift.async.AsyncMethodCallback<AccountDetails> resultHandler) throws org.apache.thrift.TException {
        iface.createAccount(args.account,resultHandler);
      }
    }

  }

  public static class createAccount_args implements org.apache.thrift.TBase<createAccount_args, createAccount_args._Fields>, java.io.Serializable, Cloneable, Comparable<createAccount_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("createAccount_args");

    private static final org.apache.thrift.protocol.TField ACCOUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("account", org.apache.thrift.protocol.TType.STRUCT, (short)1);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new createAccount_argsStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new createAccount_argsTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable Account account; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      ACCOUNT((short)1, "account");

      private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // ACCOUNT
            return ACCOUNT;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByName(java.lang.String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final java.lang.String _fieldName;

      _Fields(short thriftId, java.lang.String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public java.lang.String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.ACCOUNT, new org.apache.thrift.meta_data.FieldMetaData("account", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Account.class)));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(createAccount_args.class, metaDataMap);
    }

    public createAccount_args() {
    }

    public createAccount_args(
      Account account)
    {
      this();
      this.account = account;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public createAccount_args(createAccount_args other) {
      if (other.isSetAccount()) {
        this.account = new Account(other.account);
      }
    }

    public createAccount_args deepCopy() {
      return new createAccount_args(this);
    }

    @Override
    public void clear() {
      this.account = null;
    }

    @org.apache.thrift.annotation.Nullable
    public Account getAccount() {
      return this.account;
    }

    public createAccount_args setAccount(@org.apache.thrift.annotation.Nullable Account account) {
      this.account = account;
      return this;
    }

    public void unsetAccount() {
      this.account = null;
    }

    /** Returns true if field account is set (has been assigned a value) and false otherwise */
    public boolean isSetAccount() {
      return this.account != null;
    }

    public void setAccountIsSet(boolean value) {
      if (!value) {
        this.account = null;
      }
    }

    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
      switch (field) {
      case ACCOUNT:
        if (value == null) {
          unsetAccount();
        } else {
          setAccount((Account)value);
        }
        break;

      }
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.Object getFieldValue(_Fields field) {
      switch (field) {
      case ACCOUNT:
        return getAccount();

      }
      throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new java.lang.IllegalArgumentException();
      }

      switch (field) {
      case ACCOUNT:
        return isSetAccount();
      }
      throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
      if (that == null)
        return false;
      if (that instanceof createAccount_args)
        return this.equals((createAccount_args)that);
      return false;
    }

    public boolean equals(createAccount_args that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_account = true && this.isSetAccount();
      boolean that_present_account = true && that.isSetAccount();
      if (this_present_account || that_present_account) {
        if (!(this_present_account && that_present_account))
          return false;
        if (!this.account.equals(that.account))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetAccount()) ? 131071 : 524287);
      if (isSetAccount())
        hashCode = hashCode * 8191 + account.hashCode();

      return hashCode;
    }

    @Override
    public int compareTo(createAccount_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = java.lang.Boolean.valueOf(isSetAccount()).compareTo(other.isSetAccount());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetAccount()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.account, other.account);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    @org.apache.thrift.annotation.Nullable
    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
    }

    @Override
    public java.lang.String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder("createAccount_args(");
      boolean first = true;

      sb.append("account:");
      if (this.account == null) {
        sb.append("null");
      } else {
        sb.append(this.account);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (account != null) {
        account.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class createAccount_argsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public createAccount_argsStandardScheme getScheme() {
        return new createAccount_argsStandardScheme();
      }
    }

    private static class createAccount_argsStandardScheme extends org.apache.thrift.scheme.StandardScheme<createAccount_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, createAccount_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // ACCOUNT
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.account = new Account();
                struct.account.read(iprot);
                struct.setAccountIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, createAccount_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.account != null) {
          oprot.writeFieldBegin(ACCOUNT_FIELD_DESC);
          struct.account.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class createAccount_argsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public createAccount_argsTupleScheme getScheme() {
        return new createAccount_argsTupleScheme();
      }
    }

    private static class createAccount_argsTupleScheme extends org.apache.thrift.scheme.TupleScheme<createAccount_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, createAccount_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetAccount()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetAccount()) {
          struct.account.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, createAccount_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.account = new Account();
          struct.account.read(iprot);
          struct.setAccountIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

  public static class createAccount_result implements org.apache.thrift.TBase<createAccount_result, createAccount_result._Fields>, java.io.Serializable, Cloneable, Comparable<createAccount_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("createAccount_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRUCT, (short)0);
    private static final org.apache.thrift.protocol.TField INVALID_ARGUMENT_EXCEPTION_FIELD_DESC = new org.apache.thrift.protocol.TField("invalidArgumentException", org.apache.thrift.protocol.TType.STRUCT, (short)1);
    private static final org.apache.thrift.protocol.TField MISSING_ARGUMENT_EXCEPTION_FIELD_DESC = new org.apache.thrift.protocol.TField("missingArgumentException", org.apache.thrift.protocol.TType.STRUCT, (short)2);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new createAccount_resultStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new createAccount_resultTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable AccountDetails success; // required
    public @org.apache.thrift.annotation.Nullable InvalidArgumentException invalidArgumentException; // required
    public @org.apache.thrift.annotation.Nullable MissingArgumentException missingArgumentException; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success"),
      INVALID_ARGUMENT_EXCEPTION((short)1, "invalidArgumentException"),
      MISSING_ARGUMENT_EXCEPTION((short)2, "missingArgumentException");

      private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          case 1: // INVALID_ARGUMENT_EXCEPTION
            return INVALID_ARGUMENT_EXCEPTION;
          case 2: // MISSING_ARGUMENT_EXCEPTION
            return MISSING_ARGUMENT_EXCEPTION;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByName(java.lang.String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final java.lang.String _fieldName;

      _Fields(short thriftId, java.lang.String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public java.lang.String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, AccountDetails.class)));
      tmpMap.put(_Fields.INVALID_ARGUMENT_EXCEPTION, new org.apache.thrift.meta_data.FieldMetaData("invalidArgumentException", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, InvalidArgumentException.class)));
      tmpMap.put(_Fields.MISSING_ARGUMENT_EXCEPTION, new org.apache.thrift.meta_data.FieldMetaData("missingArgumentException", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, MissingArgumentException.class)));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(createAccount_result.class, metaDataMap);
    }

    public createAccount_result() {
    }

    public createAccount_result(
      AccountDetails success,
      InvalidArgumentException invalidArgumentException,
      MissingArgumentException missingArgumentException)
    {
      this();
      this.success = success;
      this.invalidArgumentException = invalidArgumentException;
      this.missingArgumentException = missingArgumentException;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public createAccount_result(createAccount_result other) {
      if (other.isSetSuccess()) {
        this.success = new AccountDetails(other.success);
      }
      if (other.isSetInvalidArgumentException()) {
        this.invalidArgumentException = new InvalidArgumentException(other.invalidArgumentException);
      }
      if (other.isSetMissingArgumentException()) {
        this.missingArgumentException = new MissingArgumentException(other.missingArgumentException);
      }
    }

    public createAccount_result deepCopy() {
      return new createAccount_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
      this.invalidArgumentException = null;
      this.missingArgumentException = null;
    }

    @org.apache.thrift.annotation.Nullable
    public AccountDetails getSuccess() {
      return this.success;
    }

    public createAccount_result setSuccess(@org.apache.thrift.annotation.Nullable AccountDetails success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    @org.apache.thrift.annotation.Nullable
    public InvalidArgumentException getInvalidArgumentException() {
      return this.invalidArgumentException;
    }

    public createAccount_result setInvalidArgumentException(@org.apache.thrift.annotation.Nullable InvalidArgumentException invalidArgumentException) {
      this.invalidArgumentException = invalidArgumentException;
      return this;
    }

    public void unsetInvalidArgumentException() {
      this.invalidArgumentException = null;
    }

    /** Returns true if field invalidArgumentException is set (has been assigned a value) and false otherwise */
    public boolean isSetInvalidArgumentException() {
      return this.invalidArgumentException != null;
    }

    public void setInvalidArgumentExceptionIsSet(boolean value) {
      if (!value) {
        this.invalidArgumentException = null;
      }
    }

    @org.apache.thrift.annotation.Nullable
    public MissingArgumentException getMissingArgumentException() {
      return this.missingArgumentException;
    }

    public createAccount_result setMissingArgumentException(@org.apache.thrift.annotation.Nullable MissingArgumentException missingArgumentException) {
      this.missingArgumentException = missingArgumentException;
      return this;
    }

    public void unsetMissingArgumentException() {
      this.missingArgumentException = null;
    }

    /** Returns true if field missingArgumentException is set (has been assigned a value) and false otherwise */
    public boolean isSetMissingArgumentException() {
      return this.missingArgumentException != null;
    }

    public void setMissingArgumentExceptionIsSet(boolean value) {
      if (!value) {
        this.missingArgumentException = null;
      }
    }

    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((AccountDetails)value);
        }
        break;

      case INVALID_ARGUMENT_EXCEPTION:
        if (value == null) {
          unsetInvalidArgumentException();
        } else {
          setInvalidArgumentException((InvalidArgumentException)value);
        }
        break;

      case MISSING_ARGUMENT_EXCEPTION:
        if (value == null) {
          unsetMissingArgumentException();
        } else {
          setMissingArgumentException((MissingArgumentException)value);
        }
        break;

      }
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      case INVALID_ARGUMENT_EXCEPTION:
        return getInvalidArgumentException();

      case MISSING_ARGUMENT_EXCEPTION:
        return getMissingArgumentException();

      }
      throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new java.lang.IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      case INVALID_ARGUMENT_EXCEPTION:
        return isSetInvalidArgumentException();
      case MISSING_ARGUMENT_EXCEPTION:
        return isSetMissingArgumentException();
      }
      throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
      if (that == null)
        return false;
      if (that instanceof createAccount_result)
        return this.equals((createAccount_result)that);
      return false;
    }

    public boolean equals(createAccount_result that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      boolean this_present_invalidArgumentException = true && this.isSetInvalidArgumentException();
      boolean that_present_invalidArgumentException = true && that.isSetInvalidArgumentException();
      if (this_present_invalidArgumentException || that_present_invalidArgumentException) {
        if (!(this_present_invalidArgumentException && that_present_invalidArgumentException))
          return false;
        if (!this.invalidArgumentException.equals(that.invalidArgumentException))
          return false;
      }

      boolean this_present_missingArgumentException = true && this.isSetMissingArgumentException();
      boolean that_present_missingArgumentException = true && that.isSetMissingArgumentException();
      if (this_present_missingArgumentException || that_present_missingArgumentException) {
        if (!(this_present_missingArgumentException && that_present_missingArgumentException))
          return false;
        if (!this.missingArgumentException.equals(that.missingArgumentException))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetSuccess()) ? 131071 : 524287);
      if (isSetSuccess())
        hashCode = hashCode * 8191 + success.hashCode();

      hashCode = hashCode * 8191 + ((isSetInvalidArgumentException()) ? 131071 : 524287);
      if (isSetInvalidArgumentException())
        hashCode = hashCode * 8191 + invalidArgumentException.hashCode();

      hashCode = hashCode * 8191 + ((isSetMissingArgumentException()) ? 131071 : 524287);
      if (isSetMissingArgumentException())
        hashCode = hashCode * 8191 + missingArgumentException.hashCode();

      return hashCode;
    }

    @Override
    public int compareTo(createAccount_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = java.lang.Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = java.lang.Boolean.valueOf(isSetInvalidArgumentException()).compareTo(other.isSetInvalidArgumentException());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetInvalidArgumentException()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.invalidArgumentException, other.invalidArgumentException);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = java.lang.Boolean.valueOf(isSetMissingArgumentException()).compareTo(other.isSetMissingArgumentException());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetMissingArgumentException()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.missingArgumentException, other.missingArgumentException);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    @org.apache.thrift.annotation.Nullable
    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
      }

    @Override
    public java.lang.String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder("createAccount_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("invalidArgumentException:");
      if (this.invalidArgumentException == null) {
        sb.append("null");
      } else {
        sb.append(this.invalidArgumentException);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("missingArgumentException:");
      if (this.missingArgumentException == null) {
        sb.append("null");
      } else {
        sb.append(this.missingArgumentException);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (success != null) {
        success.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class createAccount_resultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public createAccount_resultStandardScheme getScheme() {
        return new createAccount_resultStandardScheme();
      }
    }

    private static class createAccount_resultStandardScheme extends org.apache.thrift.scheme.StandardScheme<createAccount_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, createAccount_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.success = new AccountDetails();
                struct.success.read(iprot);
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 1: // INVALID_ARGUMENT_EXCEPTION
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.invalidArgumentException = new InvalidArgumentException();
                struct.invalidArgumentException.read(iprot);
                struct.setInvalidArgumentExceptionIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // MISSING_ARGUMENT_EXCEPTION
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.missingArgumentException = new MissingArgumentException();
                struct.missingArgumentException.read(iprot);
                struct.setMissingArgumentExceptionIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, createAccount_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          struct.success.write(oprot);
          oprot.writeFieldEnd();
        }
        if (struct.invalidArgumentException != null) {
          oprot.writeFieldBegin(INVALID_ARGUMENT_EXCEPTION_FIELD_DESC);
          struct.invalidArgumentException.write(oprot);
          oprot.writeFieldEnd();
        }
        if (struct.missingArgumentException != null) {
          oprot.writeFieldBegin(MISSING_ARGUMENT_EXCEPTION_FIELD_DESC);
          struct.missingArgumentException.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class createAccount_resultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public createAccount_resultTupleScheme getScheme() {
        return new createAccount_resultTupleScheme();
      }
    }

    private static class createAccount_resultTupleScheme extends org.apache.thrift.scheme.TupleScheme<createAccount_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, createAccount_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        if (struct.isSetInvalidArgumentException()) {
          optionals.set(1);
        }
        if (struct.isSetMissingArgumentException()) {
          optionals.set(2);
        }
        oprot.writeBitSet(optionals, 3);
        if (struct.isSetSuccess()) {
          struct.success.write(oprot);
        }
        if (struct.isSetInvalidArgumentException()) {
          struct.invalidArgumentException.write(oprot);
        }
        if (struct.isSetMissingArgumentException()) {
          struct.missingArgumentException.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, createAccount_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(3);
        if (incoming.get(0)) {
          struct.success = new AccountDetails();
          struct.success.read(iprot);
          struct.setSuccessIsSet(true);
        }
        if (incoming.get(1)) {
          struct.invalidArgumentException = new InvalidArgumentException();
          struct.invalidArgumentException.read(iprot);
          struct.setInvalidArgumentExceptionIsSet(true);
        }
        if (incoming.get(2)) {
          struct.missingArgumentException = new MissingArgumentException();
          struct.missingArgumentException.read(iprot);
          struct.setMissingArgumentExceptionIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

}
