//
// Autogenerated by Thrift Compiler (0.12.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./bank_types');
//HELPER FUNCTIONS AND STRUCTURES

var AccountService_getAccountDetails_args = function(args) {
  this.pesel = null;
  if (args) {
    if (args.pesel !== undefined && args.pesel !== null) {
      this.pesel = args.pesel;
    }
  }
};
AccountService_getAccountDetails_args.prototype = {};
AccountService_getAccountDetails_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.pesel = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AccountService_getAccountDetails_args.prototype.write = function(output) {
  output.writeStructBegin('AccountService_getAccountDetails_args');
  if (this.pesel !== null && this.pesel !== undefined) {
    output.writeFieldBegin('pesel', Thrift.Type.STRING, 1);
    output.writeString(this.pesel);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var AccountService_getAccountDetails_result = function(args) {
  this.success = null;
  this.authorizationException = null;
  this.missingArgumentException = null;
  if (args instanceof ttypes.AuthorizationException) {
    this.authorizationException = args;
    return;
  }
  if (args instanceof ttypes.MissingArgumentException) {
    this.missingArgumentException = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.AccountDetails(args.success);
    }
    if (args.authorizationException !== undefined && args.authorizationException !== null) {
      this.authorizationException = args.authorizationException;
    }
    if (args.missingArgumentException !== undefined && args.missingArgumentException !== null) {
      this.missingArgumentException = args.missingArgumentException;
    }
  }
};
AccountService_getAccountDetails_result.prototype = {};
AccountService_getAccountDetails_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.AccountDetails();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.authorizationException = new ttypes.AuthorizationException();
        this.authorizationException.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.missingArgumentException = new ttypes.MissingArgumentException();
        this.missingArgumentException.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AccountService_getAccountDetails_result.prototype.write = function(output) {
  output.writeStructBegin('AccountService_getAccountDetails_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.authorizationException !== null && this.authorizationException !== undefined) {
    output.writeFieldBegin('authorizationException', Thrift.Type.STRUCT, 1);
    this.authorizationException.write(output);
    output.writeFieldEnd();
  }
  if (this.missingArgumentException !== null && this.missingArgumentException !== undefined) {
    output.writeFieldBegin('missingArgumentException', Thrift.Type.STRUCT, 2);
    this.missingArgumentException.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var AccountServiceClient = exports.Client = function(output, pClass) {
  this.output = output;
  this.pClass = pClass;
  this._seqid = 0;
  this._reqs = {};
};
AccountServiceClient.prototype = {};
AccountServiceClient.prototype.seqid = function() { return this._seqid; };
AccountServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };

AccountServiceClient.prototype.getAccountDetails = function(pesel, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getAccountDetails(pesel);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getAccountDetails(pesel);
  }
};

AccountServiceClient.prototype.send_getAccountDetails = function(pesel) {
  var output = new this.pClass(this.output);
  var params = {
    pesel: pesel
  };
  var args = new AccountService_getAccountDetails_args(params);
  try {
    output.writeMessageBegin('getAccountDetails', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

AccountServiceClient.prototype.recv_getAccountDetails = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new AccountService_getAccountDetails_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.authorizationException) {
    return callback(result.authorizationException);
  }
  if (null !== result.missingArgumentException) {
    return callback(result.missingArgumentException);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getAccountDetails failed: unknown result');
};
var AccountServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
};
AccountServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
};
AccountServiceProcessor.prototype.process_getAccountDetails = function(seqid, input, output) {
  var args = new AccountService_getAccountDetails_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getAccountDetails.length === 1) {
    Q.fcall(this._handler.getAccountDetails.bind(this._handler),
      args.pesel
    ).then(function(result) {
      var result_obj = new AccountService_getAccountDetails_result({success: result});
      output.writeMessageBegin("getAccountDetails", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      if (err instanceof ttypes.AuthorizationException || err instanceof ttypes.MissingArgumentException) {
        result = new AccountService_getAccountDetails_result(err);
        output.writeMessageBegin("getAccountDetails", Thrift.MessageType.REPLY, seqid);
      } else {
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getAccountDetails", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.getAccountDetails(args.pesel, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined') || err instanceof ttypes.AuthorizationException || err instanceof ttypes.MissingArgumentException) {
        result_obj = new AccountService_getAccountDetails_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("getAccountDetails", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getAccountDetails", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
